demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('lito.urls')),
    url(r'', include('users.urls')),
]

lito/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # 1. Landing Page 
    url(r'^$', views.landing_page, name='landing_page'),
    
    # Writer's URLs
    # 2. Story list page
    url(r'^story/$', views.story_list, name='story_list'),
    # 3. Create new story
    url(r'^story/new/$', views.story_new, name='story_new'),
    # 4. Story detail page (create/edit/delete story points)
    url(r'^story/(?P<pk>[0-9]+)/$', views.story_detail, name='story_detail'),
    # Create new story point
    url(r'^story_point/new/(?P<pk>\d+)/$', views.story_point_new, name='story_point_new'),
    # See a single story point
    url(r'^story_point/(?P<pk>[0-9]+)/$', views.story_point_detail, name='story_point_detail'),
    # Reader's URLs
    url(r'^reader_view/(?P<pk>[0-9]+)/$', views.reader_view, name='reader_view'),
    # Cheating API for the reader view | Later add Django REST to filter story
    url(r'^story_points_json/(?P<pk>[0-9]+)/$', views.story_points_json, name='story_points_json'),
]

users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^login/$', 'django.contrib.auth.views.login', name='signin'),
	url(r'^logout/$', 'django.contrib.auth.views.logout'),
    url(r'^signup/$', views.register, name='register'),

]

lito/models.py
from django.db import models
from django.utils import timezone

class Story (models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=500, null=True)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class StoryPoint (models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    location_name = models.CharField(max_length=200)
    text = models.TextField()
    published_date = models.DateTimeField(
            blank=True, null=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True) 
    story = models.ForeignKey(Story)
    img_url = models.URLField(max_length=200, null=True, blank=True)
    soundcloud_url = models.URLField(max_length=200, null=True, blank=True)
    youtube_url = models.URLField(max_length=200, null=True, blank=True)
    num_order = models.PositiveSmallIntegerField()

    

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Location (models.Model):
	latitude = models.DecimalField(max_digits=9, decimal_places=6)
	longitute = models.DecimalField(max_digits=9, decimal_places=6) 
	location_name = models.CharField(max_length=200)

users/models.py
from django.db import models

# Create your models here.

lito/forms.py
from django import forms
from .models import StoryPoint, Story
from django.forms import Textarea


class StoryPointForm(forms.ModelForm):

    class Meta:
        model = StoryPoint
        fields = ('title', 'location_name', 'latitude', 'longitude', 'text',
                  'img_url','soundcloud_url', 'youtube_url',)
        

class StoryForm(forms.ModelForm):

    class Meta:
        model = Story
        fields = ('title', 'description',)
        widgets = {
            'description': Textarea(attrs={'cols': 50, 'rows': 5}),
        }

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

lito/views.py
from django.shortcuts import render, get_object_or_404
from .models import StoryPoint, Story, Location
import json
from django.http import HttpResponse
from django.core import serializers
from .forms import StoryPointForm, StoryForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


def landing_page(request):
    story_list = Story.objects.all()
    return render(request, 'lito/landing_page.html', {'story_list': story_list})

@login_required
def story_list(request):
    author = request.user
    story_list = Story.objects.filter(author=author)
    return render(request, 'lito/story_list.html', {'story_list': story_list})

@login_required
def story_new(request):
    form = StoryForm()
    return render(request, 'lito/story_edit.html', {'form': form})

@login_required
def story_new(request):
    if request.method == "POST":
        form = StoryForm(request.POST)
        if form.is_valid():
            story = form.save(commit=False)
            story.author = request.user
            story.save()
            return redirect('story_detail', pk=story.pk)
    else:
        form = StoryForm()
    return render(request, 'lito/story_edit.html', {'form': form})

@login_required
def story_detail(request, pk):
    story = get_object_or_404(Story, pk=pk)
    story_points_list = StoryPoint.objects.filter(story=story).order_by('num_order')
    return render(request, 'lito/story_detail.html', {'story': story, 'story_points_list': story_points_list})

def story_point_detail(request, pk):
    story_point = get_object_or_404(StoryPoint, pk=pk)
    return render(request, 'lito/story_point_detail.html', {'story_point': story_point})

def story_point_new(request):
    add_story_point = StoryPointForm()
    return render(request, 'lito/story_point_edit.html', {'form': form})

@login_required
def story_point_new(request, pk):
    if request.method == "POST":
        form = StoryPointForm(request.POST)
        story = get_object_or_404(Story, pk=pk)
        if form.is_valid():
            story_point = form.save(commit=False)
            story_point.author = request.user
            story_point.story = story
            if story_point.youtube_url:
                story_point.youtube_url = parse_yt_url(story_point.youtube_url)
            story_point.num_order = set_num_order(story)
            story_point.save()
            return redirect('story_point_detail', pk=story_point.pk)
    else:
        form = StoryPointForm()
    return render(request, 'lito/story_point_edit.html', {'form': form})

def reader_view(request, pk):
    story = get_object_or_404(Story, pk=pk)
    story_points_list = StoryPoint.objects.filter(story=story).order_by('num_order')
    return render(request, 'lito/reader_view.html', {'story': story, 'story_points_list': story_points_list})

def story_points_json(request, pk):
    story = get_object_or_404(Story, pk=pk)
    storypoints_as_json = serializers.serialize('json', StoryPoint.objects.filter(story=story).order_by('num_order'))
    return HttpResponse(json.dumps(storypoints_as_json), content_type='application/json')

def parse_yt_url(url):
    embed_url = "https://www.youtube.com/embed/{}"
    return embed_url.format(url.split("=")[1])

def set_num_order(story):
    story_points_list = StoryPoint.objects.filter(story=story).order_by('num_order')
    print(story_points_list)
    try:
        largest = max(story_point.num_order for story_point in story_points_list)
    except ValueError:
        return 1

    return largest + 1

users/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            # Log the user in automatically in next two lines
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            # TODO Redirect should be updated to request the '?next='' paramter
            return HttpResponseRedirect("/story/")
    else:
        form = UserCreationForm()
    return render(request, "registration/signup.html", {
        'form': form,
    })

def user(request):
    user = User.objects.all()
    return render(request, 'users/signin.html', {'user': user})

lito/templates/lito/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Literograph</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <script type="text/javascript"
      src="//maps.googleapis.com/maps/api/js?key=AIzaSyDoNg_gdB6dvOIbHX-X9Ee6Kj6mBmOLSMw&libraries=places">
    </script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/lito.css' %}">
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/2.1.0/jquery.scrollTo.min.js"></script>
        <style>
          html, body {
            height: 100%;
            margin: 0;
            padding: 0;
          }
          #map {
            height: 65%;
            width: 100%;
          }
          #map_detail {
            height: 65%;
            width: 100%;
          }
          #map_search{
            height: 75%;
            width: 100%;
          }

          .controls {
            margin-top: 10px;
            border: 1px solid transparent;
            border-radius: 2px 0 0 2px;
            box-sizing: border-box;
            -moz-box-sizing: border-box;
            height: 32px;
            outline: none;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
          }

          #pac-input {
            background-color: #fff;
            font-family: Roboto;
            font-size: 15px;
            font-weight: 300;
            margin-left: 12px;
            padding: 0 11px 0 13px;
            text-overflow: ellipsis;
            width: 300px;
          }

          #pac-input:focus {
            border-color: #4d90fe;
          }

          .pac-container {
            font-family: Roboto;
          }

          #type-selector {
            color: #fff;
            background-color: #4d90fe;
            padding: 5px 11px 0px 11px;
          }

          #type-selector label {
            font-family: Roboto;
            font-size: 13px;
            font-weight: 300;
          }
          #target {
            width: 345px;
          }


        </style>
    </head>
    <body>
    <div class="page-header">

        <h1><a href="/">Literograph</a></h1>

      <div class="user">
      {{ user }}
      {% if user.is_anonymous %}
      <a href="{% url 'django.contrib.auth.views.login' %}">login</a>
      {% else %}
      <a href="{% url 'django.contrib.auth.views.logout' %}">logout</a>
      {% endif %}
    </div>





    </div>





    <div class="content container">
        <div class="row">
            <div class="col-md-12">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

lito/templates/lito/landing_page.html
{% extends 'lito/base.html' %}

    {% block content %}

    <div class="row">
      
        <div class="col-md-6">
            <h1>Read a Story</h1>

            {% for story in story_list %}
                <div>
                    <h3><a href="{% url 'reader_view' pk=story.pk %}" title="{{ story.description }}">{{ story.title }}</a></h3>
                    <p>By: {{ story.author }}</p>
                </div>
            {% endfor %}
        </div>


        <div class="col-md-6">
            <h1>Write your own Story</h1>
        </div>



        

        <div>
            {% if user.is_anonymous %}
            <div>

                <a href="{% url 'register' %}?next={% url 'story_list' %}" type="button" class="btn btn-default custom"  >| Sign Up |</a>
            </div>
            <br><br>
            
            <div>
                <a href="{% url 'signin' %}?next={% url 'story_list' %}" type="button" class="btn btn-default custom"  >| Sign In |</a>
            </div>
            {% else %}
            <div> 
                <a href="{% url 'story_list' %}" type="button" class="btn btn-default custom"  >| Go! |</a>
            </div>
              {% endif %}

        </div>

    </div>


    

    


    {% endblock %}

lito/templates/lito/reader_view.html
{% extends 'lito/base.html' %}
{% load staticfiles%}
{% block content %}
    <div class="reader_view">
    <div id="story">
        <div id="story_data" pk="{{ story.pk }}"></div>
        <div class="row">
         <div class="col-md-12">
            <h1>{{ story.title }}</h1>
        </div>


        <div class="col-md-6 scrollable">
            <div id="story_points" class="story_points">
                {% if story_points_list %}
                {% for story_point in story_points_list %}
                <div id="{{ story_point.num_order }}" class="story_point">
                    <h3>{{ story_point.num_order }}. {{ story_point.title }}</h3>
                    <p>(@{{ story_point.location_name }})</p>
                    {% if story_point.img_url %}
                        <img src="{{ story_point.img_url }}" width="100%" >
                    {% endif %}
                    {% if story_point.soundcloud_url %}
                    <iframe width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url={{ story_point.soundcloud_url }}&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
                    {% endif %}
                    {% if story_point.youtube_url %}
                        <iframe width="560" height="315" src="{{ story_point.youtube_url }}" frameborder="0" allowfullscreen></iframe>
                    {% endif %}

                        <div class="text">{{ story_point.text }}</div>

                </div>
                {% endfor %}
                {% else %}

                <div>
                    <p>The author hasn't write anything here yet. Please come back later.</p>
                </div>
                {% endif %}

            </div>
        </div>

        <div class="col-md-6">
           <div id="map">
           </div>
        </div>




        </div>

    </div>
    </div>

    <script type="text/javascript" src="{% static 'js/lito.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.waypoints.min.js' %}"></script>

{% endblock %}

lito/templates/lito/story_detail.html
{% extends 'lito/base.html' %}

{% block content %}
    <div class="writer_view">
      <div id="story_point_list">  
        <div class="row">
      
        <div class="col-md-6">
            <h1>Story Title: {{ story.title }}</h1>
            
            <a href="{% url 'reader_view' pk=story.pk %}" type="button" class="btn btn-default custom" >| Read Story |</a>
            <br><br>

            <h2>Story Points</h2>
            <p>By: {{ story.author }}</p>

            {% if story_points_list %}
            {% for story_point in story_points_list %}
                <div>
                    <h3><a href="{% url 'story_point_detail' pk=story_point.pk %}">{{ story_point.num_order }}. {{ story_point.title }}</a></h3>    
                </div>
            {% endfor %}
            {% else %}

            <div>
                <h3>You haven't writen any story points yet. Click the button on the right to start writing.</h3> 
            </div>



            {% endif %}
        </div>

         <div class="col-md-6">
            <h1>Write a new Story Point</h1>
        </div>

        <div>
            <a href="{% url 'story_point_new' pk=story.pk %}" type="button" class="btn btn-default custom" >| Add Story Point |</a>
        </div>

    </div>


      </div>
    </div>


{% endblock %}

lito/templates/lito/story_edit.html
{% extends 'lito/base.html' %}

{% block content %}
    <h1>New Story </h1>
    <form method="POST" class="story-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

{% endblock %}

lito/templates/lito/story_list.html
{% extends 'lito/base.html' %}

{% block content %}
    <div class="writer_view">
      <div id="story_list">
        <div class="row">

        <div class="col-md-6">
            <h1>Your Stories</h1>

            {% if story_list %}
            {% for story in story_list %}
                <div>
                    <h3><a href="{% url 'story_detail' pk=story.pk %}">{{ story.title }}</a></h3>
                    <p>By: {{ story.author }}</p>
                </div>
            {% endfor %}
            {% else %}

            <div>
                <h2>You haven't writen any stories yet. Click the button on the right to start writing.</h2>
            </div>



            {% endif %}
        </div>


        <div class="col-md-6">
            <h1>Write a new Story</h1>
        </div>

        <div>
            <a href="{% url 'story_new' %}" type="button" class="btn btn-default custom" >| Start Writing |</a>
        </div>

    </div>


      </div>
    </div>
{% endblock %}

lito/templates/lito/story_point_detail.html
{% extends 'lito/base.html' %}

{% block content %}
    <div class="story_point_detail">
    <a href="{% url 'story_detail' pk=story_point.story.pk %}" type="button" class="btn btn-ldefault custom" >| Back |</a>
      <h1>{{ story_point.num_order }}. {{ story_point.title }}</h1>
        {% if story_point.location_name %}
            <div class="location">
                <h2>(@{{ story_point.location_name }})</h2>
                Latitude: {{story_point.latitude}},
                Longitude: {{story_point.longitude}}

                <div id="map_detail"></div>
            </div>
        {% endif %}


        {% if story_point.img_url %}
          <img src="{{ story_point.img_url }}" width="100%" >
        {% endif %}
        {% if story_point.soundcloud_url %}
          <iframe width="100%" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url={{ story_point.soundcloud_url }}&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
        {% endif %}
        {% if story_point.youtube_url %}
          <iframe width="560" height="315" src="{{ story_point.youtube_url }}" frameborder="0" allowfullscreen></iframe>
        {% endif %}
        <p>{{ story_point.text|linebreaks }}</p>



    <script>

      function initMap() {
        var myLatLng = {lat: {{story_point.latitude}}, lng: {{story_point.longitude}}};

        var map = new google.maps.Map(document.getElementById('map_detail'), {
          zoom: 12,
          center: myLatLng
        });

        var marker = new google.maps.Marker({
          position: myLatLng,
          map: map,
          title: 'Hello World!'
        });
      }

      // Creates Map
      $(document).ready(function() {
        initMap();

      });


    </script>


    </div>


{% endblock %}

lito/templates/lito/story_point_edit.html
{% extends 'lito/base.html' %}

{% block content %}

  <div class="row">
      
        <div class="col-md-12">
          <h1>New Story Point</h1>
        </div>

        <div class="col-md-6">
            <form method="POST" class="story_point-form">{% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="save btn btn-default">Save</button>
            </form>
        </div>

        <div class="col-md-6">
          <input id="pac-input" class="controls" type="text" placeholder="Search Box">
          <div id="map_search"></div>
        </div>
        
  </div>


        

    <script>

      function initMap() {
        var nyc = {lat: 40.782864, lng: -73.967549};

        var map = new google.maps.Map(document.getElementById('map_search'), {
          zoom: 12,
          center: nyc
        });

        google.maps.event.addListener(map, "click", function (e) {
            //lat and lng is available in e object
            var latLng = e.latLng;

            var lat = latLng.lat();
            var lat = lat.toFixed(6);

            var lng = latLng.lng();
            var lng = lng.toFixed(6);

            console.log(lat, lng);

            $("#id_latitude").val(lat);

            $("#id_longitude").val(lng);

        });

        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

        var markers = [];
        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
          var places = searchBox.getPlaces();

          if (places.length == 0) {
            return;
          }

          // Clear out the old markers.
          markers.forEach(function(marker) {
            marker.setMap(null);
          });
          markers = [];

          // For each place, get the icon, name and location.
          var bounds = new google.maps.LatLngBounds();
          places.forEach(function(place) {
            var icon = {
              url: place.icon,
              size: new google.maps.Size(71, 71),
              origin: new google.maps.Point(0, 0),
              anchor: new google.maps.Point(17, 34),
              scaledSize: new google.maps.Size(25, 25)
            };

            // Create a marker for each place.
            markers.push(new google.maps.Marker({
              map: map,
              icon: icon,
              title: place.name,
              position: place.geometry.location
            }));

            if (place.geometry.viewport) {
              // Only geocodes have viewport.
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
          });
          map.fitBounds(bounds);
        
        });

      }

      // Creates Map
      $(document).ready(function() {
        initMap();

      });




    </script>


    </div>


{% endblock %}